### PR TITLE
feat: add ability to reference a config not in the same repo

### PR DESCRIPTION
**Pull request by wespickett**
Tested here:
https://github.com/wespickett/action-test/pull/1/files

### CODE REVIEW

**Comment by wespickett-cb** [comment]
@angelikatyborska Hi, it looks like you are the maintainer for this repo? I forked it to add a new feature and created this PR to contribute it back. Please let me know your thoughts/if you want any changes. Thanks!

**Comment by wespickett** [comment]
@angelikatyborska Hi, it looks like you are the maintainer for this repo? I forked it to add a new feature and created this PR to contribute it back. Please let me know your thoughts/if you want any changes. Thanks!

**Comment by angelikatyborska** [comment]
Hi! Yes. I'll take a look on the weekend

**Comment by angelikatyborska** [comment]
Can you please describe to me what kind of problem this feature would be solving? What's stopping you from keeping the configuration file in the same repository?

**Comment by wespickett** [comment]
@angelikatyborska The use case is when I have a shared workflow that uses your action that I can reference from other workflows. Since the workflow using exercism/pr-commenter-action is shared, I need the template file to also be shared (and not have to copy it into every repo using the workflow)

**Comment by angelikatyborska** [comment]
Alright. At first I wasn't sure if this is an expected feature of a GitHub action, but I see that the very popular https://github.com/EndBug/label-sync action offers that too. Except that they offer passing a URL, which allows you to fetch the file from anywhere, not just GitHub. Did you consider that approach? I'm not saying it's better than `owner/repo@ref:path`, just want to brainstorm a little before committing to one implementation 🙂. Do you know any other GitHub actions that offer reading a remote config and what syntax they offer?

Excuse me uncertainty, but I'm not very experienced with GitHub actions except for building this one, so I just want to be sure that I'm doing the right thing.

**Comment by wespickett** [comment]
@angelikatyborska Yep, the format is just the standard actions reference format `owner/repo@ref` plus ':' plus the path. I don't think using a URL in this case and being able to fetch from anywhere would be better in this case. As it would open up a whole lot more possible issues, and would also be a lot more work to maintain. By doing it this way we are just reusing the same code path for the same repo/other repo cases. I would say start out with keeping it simple -- there's no point spending extra time supporting extra features that haven't been asked for, and might never be asked for.

**Comment by angelikatyborska** [comment]
Ok, let's do this. I'll push a tiny change, test it myself and approve.

**Review by angelikatyborska — APPROVED** [review]

**Comment by angelikatyborska** [comment]
Released in 1.5.0

**Pull request merged**
