### PR TITLE
Upgrade NodeJS to 20.6.1

### PR DESCRIPTION
**Pull request by OneideLuizSchneider**

### CODE REVIEW

**Comment by angelikatyborska** [comment]
Hi! Thanks for bringing this to my attention. Node 16 had its end of life date two days ago 🙂 

I noticed you're not updating the most important field that specifies the node version - the field `runs.using` in the `action.yml`. If I were to accept the PR as is, it would mean developing and testing the action against a different node version that is actually used to run it.

Of course the ideal course of action would be to update the node version everywhere, but I just learned that running Github actions on node18 is not supported, see: https://github.com/orgs/community/discussions/53217

Node 20 is supported by the Github action runner, and 20 will be the next LTS version, so we should just use that. Could you update your PR to use the latest node 20 version instead, also in the `action.yml` file?

**Comment by OneideLuizSchneider** [comment]
Hi @angelikatyborska 
I just upgraded it.

**Comment by angelikatyborska** [comment]
Thank you!

**Comment by angelikatyborska** [comment]
Dependencies need to be upgraded to fix the `npm build` task, but there are some breaking changes that cause the action to break. I will continue testing and fixing it some other day.

**Comment by OneideLuizSchneider** [comment]
cool, let me know if you need any help, I just saw the `build` command as well, I din't run it before, I'd only tested `lint` and `test`.

**Comment by angelikatyborska** [comment]
I managed to get everything working. Thanks again 🙏

**Comment by OneideLuizSchneider** [comment]
Great, Thanks @angelikatyborska

**Pull request merged**
